services:
  # A web service for the Next.js application
  - type: web
    name: selfcast-platform
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: selfcast-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: APP_URL
        value: https://selfcast-platform.onrender.com
    plan: starter
    # Automatic branch deploys for the main branch
    autoDeploy: true
    
  # Keep-alive worker to prevent instance from spinning down
  - type: worker
    name: selfcast-keep-alive
    env: node
    buildCommand: npm ci
    startCommand: npm run keep-alive
    envVars:
      - key: APP_URL
        value: https://selfcast-platform.onrender.com
    plan: starter
    # Automatic branch deploys for the main branch
    autoDeploy: true

databases:
  # MongoDB instance
  - name: selfcast-mongodb
    plan: free
    type: mongodb
